name: cycle-editor

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    working-directory: ./desktop/CycleEditor
env:
  OUT_DIR: "/tmp/out"
  DIST_DIR: "/tmp/out/dist"
  GRADLE_HOME: ${{ github.workspace }}/gradle-home

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      # These setup steps should be common across all jobs in this workflow.
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build wth Maven
        run: mvn --batch-mode --update-snapshots verify

  lint:
    name: Lint
    needs: checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@v0.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'Checkstyle'
